# Generated by Django 5.2.7 on 2025-11-01 11:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=160, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('module', models.CharField(db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_single', models.BooleanField(default=False)),
                ('is_child', models.BooleanField(default=False)),
                ('is_tree', models.BooleanField(default=False)),
                ('is_submittable', models.BooleanField(default=False)),
                ('naming_rule', models.CharField(choices=[('set_by_user', 'set_by_user'), ('autoincrement', 'autoincrement'), ('series', 'series'), ('field', 'field'), ('format', 'format')], default='set_by_user', max_length=20)),
                ('naming_series', models.CharField(blank=True, max_length=120, null=True)),
                ('naming_field', models.CharField(blank=True, max_length=120, null=True)),
                ('naming_format', models.CharField(blank=True, max_length=200, null=True)),
                ('title_field', models.CharField(blank=True, max_length=120, null=True)),
                ('search_fields', models.CharField(blank=True, max_length=400, null=True)),
                ('default_view', models.CharField(default='list', max_length=20)),
                ('sort_by', models.CharField(default='modified', max_length=120)),
                ('sort_order', models.CharField(default='DESC', max_length=4)),
                ('icon', models.CharField(blank=True, max_length=60, null=True)),
                ('color', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocPerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9 _.-]+$', 'Invalid role')])),
                ('read', models.BooleanField(default=True)),
                ('create', models.BooleanField(default=False)),
                ('write', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('submit', models.BooleanField(default=False)),
                ('cancel', models.BooleanField(default=False)),
                ('row_filter', models.TextField(blank=True, null=True)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perm_set', to='orbit_core.doctype')),
            ],
            options={
                'unique_together': {('doctype', 'role')},
            },
        ),
        migrations.CreateModel(
            name='DocField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveIntegerField(db_index=True, default=0)),
                ('fieldname', models.SlugField(max_length=160)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('index', models.BooleanField(default=False)),
                ('default', models.TextField(blank=True, null=True)),
                ('options', models.TextField(blank=True, null=True)),
                ('link_to', models.CharField(blank=True, max_length=160, null=True)),
                ('table_doctype', models.CharField(blank=True, max_length=160, null=True)),
                ('precision', models.IntegerField(blank=True, null=True)),
                ('read_only', models.BooleanField(default=False)),
                ('visible_roles', models.CharField(blank=True, max_length=500, null=True)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_set', to='orbit_core.doctype')),
            ],
            options={
                'ordering': ['idx'],
                'unique_together': {('doctype', 'fieldname')},
            },
        ),
    ]
